# Generated by Django 5.1.7 on 2025-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0009_profile_created_on_profile_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_picture',
            field=models.FileField(blank=True, upload_to='.dp'),
        ),
    ]
