[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main

[mypy.plugins.django-stubs]
django_settings_module = your_project.settings

[mypy_django_plugin]
ignore_missing_model_attributes = True
