# Generated by Django 5.1.7 on 2025-03-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
