# Generated by Django 5.1.7 on 2025-03-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0005_rename_uploaded_by_file_uploaded_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='descriptin',
        ),
    ]
