# Generated by Django 5.1.7 on 2025-03-31 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0006_rename_description_file_descriptin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='descriptin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_y',
            new_name='uploaded_by',
        ),
    ]
