# Generated by Django 5.1.7 on 2025-04-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0007_rename_descriptin_file_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(),
        ),
    ]
