# Generated by Django 5.1.7 on 2025-04-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickshare', '0010_alter_profile_display_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
